{
    "name": "ODFE Restaurant POS",
    "version": "19.0.1.0.0",
    "category": "Restaurant/POS",
    "summary": "Restaurant Point of Sale System",
    "description": "Complete Restaurant POS with session management, order handling, cart, receipts, and order history.",
    "author": "ODFE",
    "website": "https://odfe.ai",
    "depends": [
        "mail",
        "odfe_base",
        "odfe_auth",
        "odfe_product",
        "odfe_payment",
        "odfe_floor",
        "odfe_customer",
        "odfe_coupon",
        "odfe_booking",
        "odfe_realtime",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/pos_security.xml",
        "data/pos_data.xml",
        "views/pos_templates.xml",
        "views/terminal_selection.xml",
        "views/customization_drawer.xml",
        "views/session_views.xml",
        "views/order_views.xml",
        "views/order_line_views.xml",
        "views/receipt_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "odfe_pos/static/src/js/utils.js",
            "odfe_pos/static/src/js/services/api_service.js",
            "odfe_pos/static/src/js/services/payment_service.js",
            "odfe_pos/static/src/js/services/kitchen_service.js",
            "odfe_pos/static/src/js/services/customer_service.js",
            "odfe_pos/static/src/js/services/promotion_service.js",
            "odfe_pos/static/src/js/services/websocket_service.js",
            "odfe_pos/static/src/js/components/product_card.js",
            "odfe_pos/static/src/js/components/category_tabs.js",
            "odfe_pos/static/src/js/components/cart_component.js",
            "odfe_pos/static/src/js/components/cart_item.js",
            "odfe_pos/static/src/js/components/order_summary.js",
            "odfe_pos/static/src/js/components/payment_button.js",
            "odfe_pos/static/src/js/components/search_bar.js",
            "odfe_pos/static/src/js/components/navbar.js",
            "odfe_pos/static/src/js/components/customer_card.js",
            "odfe_pos/static/src/js/components/table_card.js",
            "odfe_pos/static/src/js/components/floor_selector.js",
            "odfe_pos/static/src/js/components/receipt_preview.js",
            "odfe_pos/static/src/js/components/qr_payment.js",
            "odfe_pos/static/src/js/screens/login_screen.js",
            "odfe_pos/static/src/js/screens/floor_popup.js",
            "odfe_pos/static/src/js/screens/order_view.js",
            "odfe_pos/static/src/js/screens/orders.js",
            "odfe_pos/static/src/js/screens/order_detail.js",
            "odfe_pos/static/src/js/screens/customer_screen.js",
            "odfe_pos/static/src/js/screens/payment_screen.js",
            "odfe_pos/static/src/js/screens/receipt_screen.js",
            "odfe_pos/static/src/js/screens/discount_popup.js",
            "odfe_pos/static/src/js/screens/table_view.js",
            "odfe_pos/static/src/js/screens/session_close.js",
            "odfe_pos/static/src/js/screens/reports_screen.js",
            "odfe_pos/static/src/js/pos_app.js",
            "odfe_pos/static/src/scss/pos_style.scss",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
