{
    'name': 'ODFE Auth',
    'version': '19.0.1.0.0',
    'category': 'Restaurant',
    'summary': 'Authentication, employee management, and role-based access for ODFE POS',
    'description': 'Extends Odoo users with restaurant-specific roles: Admin, Manager, Cashier, Kitchen, Waiter.',
    'author': 'ODFE',
    'website': 'https://odfe.app',
    'license': 'LGPL-3',
    'depends': ['odfe_base', 'base', 'mail'],
    'data': [
        'security/odfe_security.xml',
        'security/ir.model.access.csv',
        'data/odfe_auth_data.xml',
        'views/res_users_views.xml',
        'views/employee_views.xml',
        'views/roles_views.xml',
        'views/menu_views.xml',
        'views/landing_page.xml',
        'views/login_page.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
