{
    'name': 'ODFE Reports & Exports',
    'version': '19.0.1.0.0',
    'category': 'Restaurant/Reports',
    'summary': 'Reporting and export functionality for ODFE Restaurant POS',
    'description': 'Provides sales, order, revenue, product, employee, and session reporting with PDF and XLSX export.',
    'author': 'ODFE',
    'website': 'https://odfe.app',
    'license': 'LGPL-3',
    'depends': [
        'odfe_pos',
        'odfe_product',
        'odfe_payment',
        'odfe_coupon',
        'odfe_auth',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/sales_report_views.xml',
        'views/order_report_views.xml',
        'views/revenue_report_views.xml',
        'views/product_report_views.xml',
        'views/employee_report_views.xml',
        'views/session_report_views.xml',
        'views/menu_views.xml',
        'templates/report_templates.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'sequence': 20,
}
