{
    'name': 'ODFE Real-time',
    'version': '19.0.1.0.0',
    'category': 'Restaurant',
    'summary': 'Real-time WebSocket, bus, notifications, and sync for ODFE POS',
    'description': 'Handles real-time updates via WebSocket, bus notifications, and data synchronization for ODFE POS.',
    'author': 'ODFE',
    'website': 'https://odfe.app',
    'license': 'LGPL-3',
    'depends': ['base', 'bus', 'odfe_base'],
    'data': [
        'security/ir.model.access.csv',
        'views/notification_views.xml',
        'views/sync_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'sequence': 5,
}
