{
    'name': 'ODFE Floor Management',
    'version': '19.0.1.0.0',
    'category': 'Restaurant',
    'summary': 'Manage restaurant floors and tables with floor plan layout',
    'description': 'Manage restaurant floors and tables with visual floor plan, status tracking, and QR code self-ordering.',
    'author': 'ODFE',
    'website': 'https://odfe.app',
    'license': 'LGPL-3',
    'depends': ['odfe_base', 'odfe_auth'],
    'data': [
        'security/ir.model.access.csv',
        'data/floor_data.xml',
        'views/floor_views.xml',
        'views/table_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'sequence': 10,
}
