from dateutil.relativedelta import relativedelta

from odoo import api, fields, models, _


class OdfeDashboardReport(models.Model):
    _name = "odfe.dashboard.report"
    _description = "Dashboard Report"
    _order = "id desc"
    _rec_name = "name"

    name = fields.Char(string="Report Name", required=True)
    report_type = fields.Selection([
        ("sales", "Sales"),
        ("orders", "Orders"),
        ("products", "Products"),
        ("customers", "Customers"),
        ("employees", "Employees"),
    ], string="Report Type", required=True, default="sales")
    date_from = fields.Datetime(string="From")
    date_to = fields.Datetime(string="To")
    report_data = fields.Json(string="Report Data")
    chart_data = fields.Json(string="Chart Data")
    generated_at = fields.Datetime(string="Generated At", readonly=True)
    generated_by = fields.Many2one("res.users", string="Generated By", readonly=True)

    company_id = fields.Many2one("res.company", string="Company", default=lambda self: self.env.company)

    def generate(self):
        self.ensure_one()
        date_from = self.date_from or fields.Datetime.now() - relativedelta(months=1)
        date_to = self.date_to or fields.Datetime.now()

        dashboard = self.env["odfe.dashboard.sales"]
        data = dashboard.get_dashboard_data(date_from, date_to, "month")

        self.write({
            "report_data": data,
            "generated_at": fields.Datetime.now(),
            "generated_by": self.env.user.id,
        })
        return True

    def get_chart_data(self, chart_type="daily_sales"):
        self.ensure_one()
        if not self.report_data:
            self.generate()

        data = self.report_data or {}

        if chart_type == "daily_sales":
            daily = data.get("daily_sales", [])
            return {
                "labels": [r["date"].strftime("%Y-%m-%d") if hasattr(r.get("date"), "strftime") else str(r.get("date", "")) for r in daily],
                "datasets": [
                    {
                        "label": _("Revenue"),
                        "data": [float(r["revenue"] or 0.0) for r in daily],
                        "type": "line",
                    },
                    {
                        "label": _("Orders"),
                        "data": [int(r["orders"] or 0) for r in daily],
                        "type": "bar",
                    },
                ],
            }
        elif chart_type == "hourly_sales":
            hourly = data.get("hourly_sales", [])
            return {
                "labels": [f"{i}:00" for i in range(24)],
                "datasets": [
                    {
                        "label": _("Revenue"),
                        "data": [float(h["revenue"]) for h in hourly],
                    },
                ],
            }
        elif chart_type == "payment_breakdown":
            payments = data.get("payment_method_breakdown", [])
            return {
                "labels": [p["method_name"] for p in payments],
                "datasets": [
                    {
                        "label": _("Payment Amount"),
                        "data": [float(p["total"] or 0.0) for p in payments],
                    },
                ],
            }
        elif chart_type == "top_products":
            products = data.get("top_products", [])
            return {
                "labels": [p["product_name"] for p in products],
                "datasets": [
                    {
                        "label": _("Revenue"),
                        "data": [float(p["total_revenue"] or 0.0) for p in products],
                    },
                    {
                        "label": _("Quantity"),
                        "data": [float(p["total_qty"] or 0) for p in products],
                    },
                ],
            }
        elif chart_type == "top_categories":
            categories = data.get("top_categories", [])
            return {
                "labels": [c["category_name"] for c in categories],
                "datasets": [
                    {
                        "label": _("Revenue"),
                        "data": [float(c["total_revenue"] or 0.0) for c in categories],
                    },
                ],
            }

        return {"labels": [], "datasets": []}

    @api.model
    def generate_scheduled_reports(self):
        reports = self.search([("report_type", "!=", False)])
        for report in reports:
            report.generate()
        return True
