import { Navigate, NavLink, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { BarChart3, ChefHat, ChevronDown, Coffee, Grid2X2, LogOut, Menu, Monitor, Package, Plus, Search, Settings2, ShoppingBag, Users, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { categories, products } from './data';
import { useAuth, usePos, roleLabel } from './store';
import { money, readableText } from './utils';
import type { Product } from './types';

function Protected() { return useAuth.getState().user ? <Outlet /> : <Navigate to="/login" replace />; }
function Shell() {
  const user = useAuth((s) => s.user)!; const logout = useAuth((s) => s.logout); const [open, setOpen] = useState(false);
  const links = user.role === 'ADMIN' ? [['/admin/products', 'Products', Package], ['/admin/categories', 'Categories', Grid2X2], ['/admin/booking', 'Booking', Settings2], ['/admin/users', 'Team', Users], ['/admin/reports', 'Reports', BarChart3], ['/kds', 'Kitchen display', ChefHat]] as const : [['/pos', 'POS terminal', ShoppingBag], ['/kds', 'Kitchen display', ChefHat]] as const;
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark">O</span><span>ODFE<small>cafe operations</small></span></div><nav>{links.map(([to, label, Icon]) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'active' : ''}><Icon size={19}/>{label}</NavLink>)}</nav><button className="logout" onClick={() => { logout(); toast.success('See you next time'); }}><LogOut size={18}/>Log out</button></aside><main className="main"><header className="topbar"><button className="icon-btn mobile-menu" onClick={() => setOpen(!open)}><Menu size={22}/></button><div><span className="eyebrow">Good morning, {user.name.split(' ')[0]}</span><h1>{useLocation().pathname.startsWith('/pos') ? 'POS terminal' : 'Workspace'}</h1></div><div className="top-actions"><span className="status-dot"/> <span className="hide-mobile">Online</span><div className="avatar">{user.name[0]}</div></div></header><Outlet /></main></div>;
}
function Auth({ signup = false }: { signup?: boolean }) {
  const login = useAuth((s) => s.login); const navigate = useNavigate(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!email || !password || (signup && (!name || password.length < 8))) return toast.error(signup ? 'Complete the form with a password of 8+ characters.' : 'Enter your email and password.'); login({ name: name || 'Alex Morgan', email, role: email.includes('admin') ? 'ADMIN' : 'EMPLOYEE' }); sessionStorage.setItem('odfe-token', 'demo-token'); navigate('/pos'); toast.success('Welcome to ODFE'); };
  return <div className="auth-page"><div className="auth-art"><div className="brand light"><span className="brand-mark">O</span><span>ODFE<small>cafe operations</small></span></div><div className="art-copy"><p className="eyebrow">Your cafe, in rhythm</p><h1>Make every<br/><em>moment</em> count.</h1><p>A calmer, warmer way to run your floor, bar and kitchen.</p></div><div className="art-foot">Designed for the places people love to return to.</div></div><div className="auth-form"><div className="mobile-brand brand"><span className="brand-mark">O</span><span>ODFE<small>cafe operations</small></span></div><div className="form-wrap"><p className="eyebrow">{signup ? 'Create your workspace' : 'Welcome back'}</p><h2>{signup ? 'Start serving better.' : 'Good to see you again.'}</h2><p className="muted">{signup ? 'Set up your cafe account in a minute.' : 'Sign in to pick up where you left off.'}</p><form onSubmit={submit}>{signup && <label>Name<input value={name} onChange={e => setName(e.target.value)} placeholder="Alex Morgan"/></label>}<label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@cafe.com"/></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder={signup ? 'At least 8 characters' : '••••••••'}/></label><button className="primary full">{signup ? 'Create account' : 'Sign in'} <span>→</span></button></form><p className="switch">{signup ? 'Already have an account?' : 'New to ODFE?'} <NavLink to={signup ? '/login' : '/signup'}>{signup ? 'Sign in' : 'Create an account'}</NavLink></p></div></div></div>;
}
function Pos() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const add = usePos(s => s.add); const cart = usePos(s => s.cart); const change = usePos(s => s.change);
  const visible = products.filter(p => (category === 'All' || p.category.name === category) && p.name.toLowerCase().includes(query.toLowerCase())); const subtotal = cart.reduce((a, l) => a + l.product.price * l.quantity, 0);
  return <section className="pos-page"><div className="pos-toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search menu..." /></div><button className="secondary"><Grid2X2 size={17}/> Table 12 <ChevronDown size={16}/></button></div><div className="pos-grid"><div className="menu-area"><div className="category-tabs">{['All', ...categories.map(c => c.name)].map(c => <button key={c} className={category === c ? 'selected' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div><div className="product-grid">{visible.map(p => <button className="product-card" key={p.id} onClick={() => { add(p); toast.success(`${p.name} added`, { id: p.id }); }}><span className="product-accent" style={{ background: p.category.color }}/><div className="product-icon" style={{ background: p.category.color, color: readableText(p.category.color) }}>{p.name[0]}</div><div className="product-info"><strong>{p.name}</strong><span>{p.description}</span><b>{money(p.price)}</b></div><span className="add"><Plus size={18}/></span></button>)}</div></div><aside className="cart"><div className="cart-head"><div><p className="eyebrow">Current order</p><h2>Table 12</h2></div><span className="count">{cart.reduce((a, l) => a + l.quantity, 0)} items</span></div>{cart.length === 0 ? <div className="empty-cart"><ShoppingBag size={30}/><strong>Your order is empty</strong><span>Tap a menu item to get started</span></div> : <div className="cart-lines">{cart.map(l => <div className="cart-line" key={l.product.id}><div><strong>{l.product.name}</strong><span>{money(l.product.price)} each</span></div><div className="qty"><button onClick={() => change(l.product.id, l.quantity - 1)}>−</button><b>{l.quantity}</b><button onClick={() => change(l.product.id, l.quantity + 1)}>+</button></div><strong>{money(l.product.price * l.quantity)}</strong></div>)}</div>}<div className="totals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Tax <small>8.5%</small></span><b>{money(subtotal * .085)}</b></div><div className="total"><strong>Total</strong><strong>{money(subtotal * 1.085)}</strong></div><button className="primary full" disabled={!cart.length} onClick={() => { toast.success('Order sent to payment'); }}>Charge {money(subtotal * 1.085)} <span>→</span></button></div></aside></div></section>;
}
function AdminPage({ title, subtitle, kind = 'table' }: { title: string; subtitle: string; kind?: string }) {
  const [search, setSearch] = useState('');
  const categoryRows = categories.filter(c => c.name.toLowerCase().includes(search.toLowerCase()));
  const productRows = products.filter(p => p.name.toLowerCase().includes(search.toLowerCase()));
  return <section className="content"><div className="page-heading"><div><p className="eyebrow">Manage</p><h2>{title}</h2><p className="muted">{subtitle}</p></div><button className="primary"><Plus size={18}/> Add {title.slice(0, -1)}</button></div><div className="panel"><div className="panel-toolbar"><div className="search"><Search size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder={`Search ${title.toLowerCase()}...`}/></div><span className="result-count">{kind === 'categories' ? categoryRows.length : kind === 'products' ? productRows.length : 0} results</span></div>{kind === 'categories' ? <div className="category-list">{categoryRows.map(c => <div className="category-row" key={c.id}><span className="swatch" style={{ background: c.color }}/><strong>{c.name}</strong><span className="muted">Color {c.color}</span><button className="text-btn">Edit</button></div>)}</div> : kind === 'products' ? <div className="data-table"><div className="tr th"><span>Product</span><span>Category</span><span>Price</span><span>Kitchen</span><span/></div>{productRows.map((p: Product) => <div className="tr" key={p.id}><span className="product-cell"><span className="mini-dot" style={{ background: p.category.color }}/><strong>{p.name}</strong></span><span className="muted">{p.category.name}</span><span className="price">{money(p.price)}</span><span><span className="pill green">{p.sendToKitchen ? 'Yes' : 'No'}</span></span><button className="text-btn">Edit</button></div>)}</div> : <div className="empty-state"><Settings2 size={28}/><strong>{title} is ready to configure</strong><span>Connect this workspace to your cafe settings when you are ready.</span></div>}</div></section>;
}
function Kds() { const [stage, setStage] = useState('New'); return <section className="content"><div className="page-heading"><div><p className="eyebrow">Live service</p><h2>Kitchen display</h2><p className="muted">Keep the pass moving. Updated just now.</p></div><span className="live"><span className="status-dot"/> Live</span></div><div className="kds-columns">{['New', 'Preparing', 'Ready'].map(column => <div className="kds-column" key={column}><div className="column-title"><strong>{column}</strong><span>1</span></div><div className="order-ticket"><div className="ticket-head"><strong>#1048</strong><span>2 min ago</span></div><h3>Table 12</h3><div className="ticket-item"><b>2×</b><span>Cappuccino</span></div><div className="ticket-item"><b>1×</b><span>Avocado Toast</span></div><button className="secondary full" onClick={() => setStage(column === 'New' ? 'Preparing' : 'Ready')}>{stage === column ? 'Move to next stage →' : `Mark ${column === 'New' ? 'preparing' : 'ready'}`}</button></div></div>)}</div></section>; }
function Display({ selfOrder = false }) { const [sent, setSent] = useState(false); return <div className="display-page"><div className="display-top"><div className="brand light"><span className="brand-mark">O</span><span>ODFE<small>cafe operations</small></span></div><span>{selfOrder ? 'Order at your table' : 'Thank you for visiting'}</span></div><div className="display-content">{sent ? <><div className="success-mark">✓</div><h1>Order received.</h1><p>Your order is now with the kitchen. We’ll bring it right over.</p><button className="primary" onClick={() => setSent(false)}>Start another order</button></> : <><p className="eyebrow">Welcome to our cafe</p><h1>Good food.<br/><em>Good company.</em></h1><p>{selfOrder ? 'Browse the menu and order from your table.' : 'Your order number will appear here when it is ready.'}</p>{selfOrder && <button className="primary" onClick={() => setSent(true)}>Browse menu <span>→</span></button>}</>}</div></div>; }
function App() { useEffect(() => { const fn = () => { useAuth.getState().logout(); window.location.href = '/login'; }; window.addEventListener('odfe:unauthorized', fn); return () => window.removeEventListener('odfe:unauthorized', fn); }, []); return <Routes><Route path="/login" element={<Auth/>}/><Route path="/signup" element={<Auth signup/>}/><Route element={<Protected/>}><Route element={<Shell/>}><Route path="/pos" element={<Pos/>}/><Route path="/pos/*" element={<Pos/>}/><Route path="/admin/products" element={<AdminPage title="Products" subtitle="Your menu, priced and ready to sell." kind="products"/>}/><Route path="/admin/categories" element={<AdminPage title="Categories" subtitle="Organise your menu with a little colour." kind="categories"/>}/><Route path="/admin/:section" element={<AdminPage title="Workspace" subtitle="Everything your team needs, in one place."/>}/><Route path="/kds" element={<Kds/>}/></Route></Route><Route path="/customer-display" element={<Display/>}/><Route path="/s/:token" element={<Display selfOrder/>}/><Route path="*" element={<Navigate to="/pos" replace/>}/></Routes>; }
export default App;
