export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const BCRYPT_SALT_ROUNDS = 12;

export const JWT_ACCESS_EXPIRES_IN = "15m";
export const JWT_REFRESH_EXPIRES_IN = "7d";

export const ROLE = {
  ADMIN: "ADMIN",
  EMPLOYEE: "EMPLOYEE",
  CUSTOMER: "CUSTOMER",
} as const;

export const AUDIT_ACTIONS = {
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGOUT_ALL: "LOGOUT_ALL",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  FAILED_LOGIN: "FAILED_LOGIN",
  CUSTOMER_SESSION: "CUSTOMER_SESSION",
} as const;

export const PASSWORD_RESET_EXPIRES_IN = 60 * 60 * 1000;
export const REFRESH_TOKEN_BYTES = 64;
export const PASSWORD_RESET_TOKEN_BYTES = 48;
