{
    'name': 'ODFE Product',
    'version': '19.0.1.0.0',
    'category': 'Restaurant',
    'summary': 'Product catalog, categories, taxes, and UoM for ODFE Restaurant POS',
    'description': 'Manages products, categories, taxes, and units of measure for the ODFE Restaurant POS system.',
    'author': 'ODFE',
    'website': 'https://odfe.app',
    'license': 'LGPL-3',
    'depends': ['odfe_base', 'product', 'uom'],
    'data': [
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'views/product_views.xml',
        'views/category_views.xml',
        'views/tax_views.xml',
        'views/uom_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'sequence': 2,
}
